################################# Default configuration ###################
baseURL = "http://airesiea.org/" # Don't forget the trailing '/' !
title = "Air ESIEA"
theme = "airspace-hugo"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "30"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
DefaultContentLanguage = "fr"
#disableLanguages = []
disableLanguages = ["en"] # TEMPORARY

#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


############################### widgets #################################

[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


############################## navigation ###############################

# FR menu
#[[Languages.fr.menu.main]]
#name = "Nos activités"
#URL = "about"
#weight = 10

#[[Languages.fr.menu.main]]
#name = "Blog"
#URL = "blog"
#weight = 20

[[Languages.fr.menu.main]]
name = "Nos projets"
URL = "projets"
weight = 30

[[Languages.fr.menu.main]]
weight = 40
name = "Espace étudiants"
hasChildren = true

  [[Languages.fr.menu.main]]
  parent = "Espace étudiants"
  name = "PSTs / Cap Projet"
  #URL = "faq"
  URL = "pst"
  weight = 41

  [[Languages.fr.menu.main]]
  parent = "Espace étudiants"
  name = "PFH"
  URL = "pfh"
  weight = 42

  [[Languages.fr.menu.main]]
  parent = "Espace étudiants"
  name = "Rejoindre l'association"
  #URL = "pricing"
  URL = "https://www.helloasso.com/associations/association-aerospatiale-air-esiea/adhesions/adhesion-a-air-esiea"
  weight = 43

  # Où nous trovuer géographique + cotiz & co

#  [[Languages.fr.menu.main]]
#  parent = "Espace étudiants"
#  name = "Base de connaissances"
#  #URL = "pricing"
#  URL = "wip"
#  weight = 44

[[Languages.fr.menu.main]]
name = "Partenaires"
#URL = "blog"
URL = "wip"
weight = 50

  [[Languages.fr.menu.main]]
  parent = "Partenaires"
  name = "Nos partenaires"
  URL = "partenaires"
  #URL = "faq"

  [[Languages.fr.menu.main]]
  parent = "Partenaires"
  name = "Nous soutenir"
  #URL = "wip"
  URL = "nous_soutenir"
  
  # Ce qu'on propose
  # choisir de sponsoriser un de nos projets
  # invite à prendre cotnact avec nous dès maintenant pour que nus puissons vous aider à nous soutenir
  # intérêt public
  
#[[Languages.fr.menu.main]]
#name = "Nous contacter"
##URL = "contact"
##URL = "wip"
#weight = 60
#
#  [[Languages.fr.menu.main]]
#  parent = "Nous contacter"
#  name = "Notre équipe"
#  #URL = "faq"
#  URL = "wip"
#
#  [[Languages.fr.menu.main]]
#  parent = "Nous contacter"
#  name = "Nos coordonnées"
#  #URL = "faq"
#  URL = "wip"

[[Languages.fr.menu.main]]
name = "Nous contacter"
URL = "contact"
#URL = "wip"
weight = 60

## footer Languages.fr.menu
#[[Languages.fr.menu.footer]]
#name = ""
#URL = "about"
#weight = 1


#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "This is meta description"
author = "Air ESIEA"
# Contact Information
mobile = ""
email = "air-esiea@et.esiea.fr"
location = "74bis Avenue Maurice Thorez, 94200 Ivry-sur-Seine"
# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io
# Google Analitycs
google_analitycs_id = "" # Your ID# search
# multi-author support (if set to true, you must use an Array in the author field)
multi_author = false

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"

# google map
[params.gmap]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "48.81446481395829"
map_longitude = "2.378390162794104"
map_marker = "images/marker.png"

  
############################# social site ########################
[[params.social]]
icon = "ion-social-googleplus-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-pinterest-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-dribbble-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"


################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Air ESIEA - Aerospace Student Association since 1986"

################################ France Language ########################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
home = "Accueil"
# copyright TEST8
copyright = "Air ESIEA - Association Aérospatiale depuis 1986"
